Добавление системы лайков и друзей.
DM-student/java-filmorate pull request #2
Opened 2023-02-15 21:24 UTC by DM-student

Доработана система лайков и друзей, также была реализована обработка ошибок и изменено хранение информации.

2023-02-16 07:44 UTC, LexLippi requested changes
Привет!

Неплохая работа!
Оставил несколько важных замечаний, которые необходимо исправить!

Желаю удачи!

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +		if(filmService.getFilmStorage().getFilm(id) == null)
Такого обращения быть не должно.
Контроллер не должен ничего знать про хранилище.

У сервиса должен быть свой метод, который инкапсулирует эту логику. Выбрасывает исключение, если фильм не найден. Контроллер не должен об этом знать.

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +		return filmService.getFilmStorage().getFilms();
Аналогично тому, что написано ниже. Контроллер не должен знать про хранилище.

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +		filmService.getFilmStorage().addFilm(film);
Отдельный метод в сервисе для добавления фильма должен быть

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +	}
Может быть это вынести в отдельный компонент?
Зачем это дублировать в каждом контроллере?

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +	public boolean isValid(Film film)
Зачем этот метод `public`?

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
>  public class UserController
Все замечания, аналогиные `FilmContoller`

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/AnnotationValidator.java
> +	private javax.validation.Validator localValidator;
А просто `Validator` нельзя написать?

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/AnnotationValidator.java
> +	}
Эту инициализацию можно заинлайнить

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +public class FilmService
Сервис это интерфейс, у которого должна быть реализация, а не просто класс

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +	}
Этого метода у сервиса не должно быть

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +	private UserService userService;
В идеале сервисы не должны использовать друг друга. Они должны использовать хранилища

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +	}
Почему не инициализировать поля одним образом?
А то для сервиса `Autowired` в одном месте, а для хранилища в другом. Это слегка ломает мозг

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +		return films.getFilms().stream().sorted(Comparator.comparingInt(x -> -x.getLikes().size()))
Лямбда - это такая же функция, как и все другие, не стоит в них использовать однобуквенные переменные.

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +		}
Название метода и ошибки противоречат друг другу.
Метод проверяет существует ли пользователь, а в ошибке указано, что пользователя не существует

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +	}
Класс, а удаление лайка где?
Все проверки есть, а удаления нет :)

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +		}
????
Две одинаковые проверки?

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +		}
Про это уже написал ниже

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +public class UserService
Аналогичное замечание про интерфейс

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +	}
Не должно быть этого метода

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +	}
Зачем и здесь, и выше `Autowired`?

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +			throw new NullPointerException("Данный фильм не найден.");
Вообще стоит использовать для такого кастомные исключения, а не `NPE`

2023-02-16 07:44 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +	}
Обычно советую не использовать цифровые идентификаторы в названиях переменных

2023-02-16 07:44 UTC, LexLippi commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +
По-хорошему изменение подхода к валидации не должно приводить к удалению существующих тестов.
В идеале, стоит подумать, как их можно оставить.

2023-02-18 09:36 UTC, LexLippi requested changes
Привет!

Неплохая работа, но некоторые комментарии, так и не были исправлены!

Желаю удачи!!!

2023-02-18 09:36 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +	public boolean isValid(Film film)
Так ещё раз зачем он `public`, если мы нигде за пределами этого класса его не используем?

2023-02-18 09:36 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +	}
Вот этот маппинг во всех контроллерах одинаковый, можно ли его вынести в общий класс?

2023-02-18 09:36 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
>  	}
Аналогичные замечания к этим методам, как и в `FilmController`

2023-02-18 09:36 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/NotFoundException.java
> +	String element;
Модификатор доступа не помешает

2023-02-18 09:36 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +	private UserService userService;
Здесь обращаю внимание ещё раз. В слоеной архитектуре не принято, чтобы взаимодействовали элементы одного слоя. В данном случае сервисы. Они должны зависеть от хранилищ

2023-02-18 09:36 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +	}
Лайк по -прежнему не удаляется

2023-02-18 09:36 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +		if(userService.userIsPresent(userId))
Здесь все осталось, как и было. Метод проверяет существует ли объект, и если он существует, то выбрасывает исключение, что объекта не существует o_0

2023-02-18 09:36 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +	}
На это ещё раз обращаю внимание

2023-02-18 09:36 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +	}
Ну, я имел в виду, что можно написать `user`, `otherUser`. Это необязательно к исправлению, но просто во-многих командах принят запрет на использование цифровых идентификаторов, возможно, в будущем к этому придется привыкать :)

2023-02-22 07:54 UTC, LexLippi requested changes
Привет!

Неплохая работа, оставил несколько комментариев, которые можно не исправлять, написал про них. Также не понимаю, почему ты до сих пор не поправишь удаление лайка, пишу тебе про это в третий раз.

Желаю удачи!!!

2023-02-22 07:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +		if(filmService.getFilm(id) == null)
Это можно не переделывать, но:

Лучше сохранять результат выполнения этого запроса в локальную переменную, так как иначе, если пользователь существует, то тебе придется дважды обратиться к СУБД (так как сейчас у нас не СУБД, а просто `HashMap`, то накладные расходы, конечно, куда меньше), что существенно замедляет работу этого метода, а если бы мы сохраняли результат в локальную переменную, то это ускорило бы работу программы.

2023-02-22 07:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +	public List<Film> getPopular(@RequestParam(required = false) Integer count)
Можно так:

```java
@RequestParam(defaultValue = 10) Integer count
```

2023-02-22 07:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +		if(userService.getUser(id) == null)
Аналогично тому, что написал в `FilmService`

2023-02-22 07:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
>  	public User ReplaceUser(@RequestBody User user)
Название метода должно быть с маленькой буквы!

2023-02-22 07:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +	}
Ровно такой же метод есть у тебя в `FilmController`.
Можно ли каким-то образом избавиться от дублирования абсолютно идентичных методов для обработки ошибок?

Подсказка: можно использовать абстрактный класс, который будет родительским для всех контроллеров

2023-02-22 07:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +		if(films.getFilm(filmId) == null)
Аналогичное замечание про сохранение в переменную

2023-02-22 07:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +		if(films.getFilm(filmId) == null)
1. Аналогично про локальную переменную (просто обращаю внимание, чтобв ты видел все эти моменты)
2. Почему ты принципиально не удаляешь из фильма лайк? Все проверки произвел, но после них нет никаких действий. Если у тебя есть какая-то тактика, то напиши её мне (здесь в ответ на этот коммент или в Пачке, или в комментарии к коду)

2023-02-22 07:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +		if(users.getUser(userId) == null)
Локальная переменная

2023-02-22 07:54 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +		if(users.getUser(userId) == null)
Локальная переменная

2023-02-22 09:41 UTC, DM-student commented
Починил лайк (очень глупая ошибка там), добавил локальные переменные, на будущее, чтобы при использовании БД не обращаться к нему постоянно при проверках. Конечно, есть пара вещей, которые я оставил без внимания, но они не критические. Буду благодарен, если пропустите ТЗ так, а то у меня малость сроки горят... К следующему ТЗ доработаю то, что не доработал сейчас.

2023-02-23 08:54 UTC, LexLippi approved these changes
Привет!

Хорошая работа, отлично, что исправил почти все замечания!

Желаю удачи в следующих спринтах!!!

2023-04-02 18:29 UTC, merged